const ActionTypes = {
  REST_LOADING: "REST_LOADING",
  REST_SUCCESS: "REST_SUCCESS",
  REST_ERROR: "REST_ERROR",

  CARD_LOADING: "CARD_LOADING",
  CARD_SUCCESS: "CARD_SUCCESS",
  CARD_ERROR: "CARD_ERROR",
  CREATE_ITEM: "CREATE_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
};

export default ActionTypes;
